"""initial schema

Revision ID: 39ec81d38c35
Revises: 
Create Date: 2026-07-02 03:12:28.123554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ec81d38c35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('slack_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('sla_hours_critical', sa.Integer(), nullable=True),
    sa.Column('sla_hours_high', sa.Integer(), nullable=True),
    sa.Column('auto_send_critical_alerts', sa.Boolean(), nullable=True),
    sa.Column('dns_baseline', sa.JSON(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_root_domain'), 'clients', ['root_domain'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_type', sa.Enum('subdomain', 'ip', 'cloud_resource', name='assettype'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_client_id'), 'assets', ['client_id'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('aws', 'gcp', 'azure', name='cloudprovider'), nullable=False),
    sa.Column('account_identifier', sa.String(length=255), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_audited_at', sa.DateTime(), nullable=True),
    sa.Column('config_baseline', sa.JSON(), nullable=True),
    sa.Column('credentials_rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_accounts_client_id'), 'cloud_accounts', ['client_id'], unique=False)
    op.create_table('compliance_controls',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('framework', sa.Enum('soc2', 'iso27001', 'india_dpdp', name='complianceframework'), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('control_name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('missing', 'in_progress', 'implemented', name='compliancecontrolstatus'), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('evidence_file_path', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_controls_client_id'), 'compliance_controls', ['client_id'], unique=False)
    op.create_table('pentest_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('frequency', sa.Enum('quarterly', 'semi_annual', 'annual', 'custom', name='pentestfrequency'), nullable=False),
    sa.Column('next_due_date', sa.DateTime(), nullable=False),
    sa.Column('last_completed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'overdue', name='penteststatus'), nullable=True),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pentest_schedules_client_id'), 'pentest_schedules', ['client_id'], unique=False)
    op.create_table('phishing_campaigns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'running', 'completed', name='phishingcampaignstatus'), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('reported_count', sa.Integer(), nullable=True),
    sa.Column('credential_submitted_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_campaigns_client_id'), 'phishing_campaigns', ['client_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_type', sa.Enum('monthly_security', 'threat_digest', name='reporttype'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('docx_path', sa.String(length=500), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_type', sa.Enum('subdomain_enum', 'port_scan', 'vuln_scan', 'cloud_audit', 'dark_web_scan', name='scantype'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='scanstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('new_assets_found', sa.Integer(), nullable=True),
    sa.Column('new_findings_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_output_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_client_id'), 'scan_runs', ['client_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'client', name='userrole'), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_client_id'), 'audit_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'in_remediation', 'resolved', 'verified', 'disputed', name='findingstatus'), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_client_id'), 'findings', ['client_id'], unique=False)
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_dedup_hash'), 'findings', ['dedup_hash'], unique=False)
    op.create_table('phishing_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_identifier', sa.String(length=255), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('reported', sa.Boolean(), nullable=True),
    sa.Column('submitted_credentials', sa.Boolean(), nullable=True),
    sa.Column('training_completed', sa.Boolean(), nullable=True),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['phishing_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_results_campaign_id'), 'phishing_results', ['campaign_id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_version', sa.String(length=255), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_asset_id'), 'ports', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ports_asset_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_phishing_results_campaign_id'), table_name='phishing_results')
    op.drop_table('phishing_results')
    op.drop_index(op.f('ix_findings_dedup_hash'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_client_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_client_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scan_runs_client_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_phishing_campaigns_client_id'), table_name='phishing_campaigns')
    op.drop_table('phishing_campaigns')
    op.drop_index(op.f('ix_pentest_schedules_client_id'), table_name='pentest_schedules')
    op.drop_table('pentest_schedules')
    op.drop_index(op.f('ix_compliance_controls_client_id'), table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.drop_index(op.f('ix_cloud_accounts_client_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_assets_client_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_clients_root_domain'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
