"""add risk_analysis to reports

Revision ID: 8d2b7ca2c7e3
Revises: 39ec81d38c35
Create Date: 2026-07-02 03:58:06.406594

Note: this was originally autogenerated, but hand-trimmed. Autogenerate
against sqlite produces spurious NUMERIC->UUID op.alter_column noise on
every id/foreign-key column, because sqlite has no native UUID type and
compare_type=True flags the custom type object as "changed" even though
nothing about the actual column changed. That noise doesn't reflect a
real schema change and is safe to drop -- it would be a no-op on
Postgres (the real deployment target) anyway, but running dozens of
pointless ALTER COLUMN statements in a migration is worth avoiding.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d2b7ca2c7e3'
down_revision: Union[str, Sequence[str], None] = '39ec81d38c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('reports', sa.Column('risk_analysis', sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column('reports', 'risk_analysis')
